services:
  app:
    build:
      context: .
    container_name: php-app-paw
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/
    environment:
      API_KEY_GEMINI: ${API_KEY_GEMINI}
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15.3
    container_name: postgres-TPI
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DBNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env

volumes:
  postgres_data: