services:
  paw-2024:
    image: postgres:15.3
    container_name: postgres-paw
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DBNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

volumes:
  postgres_data: